# Generated by Django 4.2.7 on 2023-12-03 00:10

import bigfive.b5.models
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Answer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('slug', models.SlugField(default=bigfive.b5.models.generate_slug, max_length=8, unique=True)),
                ('sex', models.CharField(choices=[('', '—'), ('F', 'Žena'), ('M', 'Muž')], max_length=1, verbose_name='Vaše pohlaví')),
                ('age_group', models.CharField(choices=[('', '—'), ('Y', '20 let nebo mladší'), ('A', '21–40 let'), ('M', '41–60 let'), ('E', '61 let nebo starší')], max_length=1, verbose_name='Vaše věková skupina')),
                ('results', models.JSONField()),
                ('created', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
