version: "3.8"

services:
  bigfive:
    volumes:
      - ./bigfive:/code/bigfive
    environment:
      DEBUG: "true"
    stdin_open: true
    tty: true
    command: python ./manage.py runserver 0:9200
